### ISSUE TITLE
MP3 plays but no visualization - Console error messages in Chrome

### ISSUE THREAD

**Issue by IndigoJay** [soundshader/soundshader.github.io#1]
Selecting MP3 works, and MP3 begins to play. However canvas remains black. Console messages pasted below:

Chromium 83.0.4103.61

At startup:

    Uncaught (in promise) TypeError: this.audioCtx.createAnalyser is not a function
    at AudioController.init (controller.js:21)
    at getAudioController (index.js:85)
    at HTMLCanvasElement.canvas.onclick (index.js:36)

At begin play:

    Uncaught (in promise) TypeError: this.audioCtx.createMediaStreamSource is not a function
    at AudioController.start (controller.js:106)
    at HTMLCanvasElement.canvas.onclick (index.js:51)

**Comment by soundshader** [comment]
createAnalyser and createMediaStreamSource are WebAudio APIs. Perhaps something is blocking it? I run it on Chrome 84.

**Comment by IndigoJay** [comment]
I upgrade to Chorme 85.0.4183.83 and turned off browser plug-ins. Everything works! What a great visualization. 

Also, be sure to recommend "Use hardware acceleration when available"
