### ISSUE TITLE
(Firefox) "Different sample-rate is currently not supported." when uploading song with 199kbps

### ISSUE THREAD

**Issue by afiaka87** [soundshader/soundshader.github.io#2]
# Overview

An error regarding sample rates occurs given a specific mp3 file. I would share the file for reproduction but it's a copyrighted work.

# MP3 file Properties
- filename: "retribution.mp3"
- bitrate: 199kbps
- length: 0:03:00
- size: 4.38 MB
- other info: converted from FLAC to mp3 using VLC's "convert/save" context menu and the "lame" codec.

# Error message
Immediately upon upload a toast notification appears in the bottom left saying:

`AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.`

After clicking the toast itself the notification's text changes to:

`start@https://soundshader.github.io/audio/controller.js:108:33
setMouseHandlers/btnUpload.onclick@https://soundshader.github.io/index.js:129:30`

which I assume to be just an unrelated click handler debug event that's now being shown because your toast is just a catch-all for debug logging. 

# Best guess
My best guess as to why this happens is because my mp3 is in an unexpected format due to me converting it from FLAC using VLC. I'll reconvert with different options and report back. 

~~_Unrelated, but it's very difficult to actually copy the initial message to the clipboard due to a click on it causing it to change. I had to use screen capture and re-type it. Keeping a persistent error message would be helpful for people who wanted to file issues. Having said that, thanks for putting some debug output upon error at all. That stuff is usually in a dev console and the increased visibility makes it easier for people who are "just stopping by" to fix their own problems/file an issue._~~ 

Edit: ^ This has since been fixed

Awesome project by the way. I felt like I was hitting a wall in finding creative techniques to visualize sound with the classic fourier analysis. Don't know how this technique has evaded me for so long.

**Comment by soundshader** [comment]
I've been wanting to test 192+ kbps audio. It must produce really nuanced images. It works with FLAC files as is, at least on desktop Ubuntu Chrome. I wouldn't convert it to mp3 as that would corrupt the waveform and the generated image in subtle ways (e.g. the image would be pixelated - that's the "jpeg" equivalent for sound).

There are a few URL parameters relevant here:

`soundshader.github.io?sr=199&fps=250&n=4096&is=2048`

- `sr=199` would set the sample rate to 199 kbps in AudioContext.
- `fps=250` would take a snapshot of sound wave every 4 ms. This means two consecutive snapshots would overlap almost entirely. This allows to capture nuanced amplitude and phase modulations, but fills the image buffer quicker, as now the entire image would capture only 1-2 sec of sound. With `fps=120`, the image would capture 3-5 sec of sound, but with 2x lower details along the radial axis.
- `n=4096` sets the size of sound snapshot to 8192 samples. In your case, it's 8192 / 192 kbps = 4 ms of sound. Careful with this param: a value too high would clog your GPU memory and everything would stall. Values too small wouldn't capture useful sound patterns, e.g. a 5000 Hz tone would make only 20 repetitions in that 4 ms window (and you'd see a 40-fold radial symmetry on the image, if my math is correct). _Must be a power of 2._
- `is=2048` is the image/canvas size. It defaults to 1024 and internally, the app uses a basic downsampling scheme, which still produces antialiasing artifacts. Higher image size would let you save the bigger image with more details. With `is=256` all the details would be lost at the downsampling phase. If you have a good GPU, you might be able to go with `is=4096`. If it doesn't work, you'd see no visuals. _Must be a power of 2._
- `pbr=1` sets the playback rate, e.g. `pbr=0.5` would play the audio 2x slower. It's sometimes useful to explore sound details.

I hear your complain about the error messages. In fact, I've been trying to debug this thing on Firefox Android and been thinking about a good way to display console logs with errors.

**Comment by soundshader** [comment]
A small correction: use `sr=199` to set custom sample rate in AudioContext.

**Comment by afiaka87** [comment]
Sorry I haven't been able to find the source of the issue despite trying various conversions and just the raw FLAC. Everything works fine in chrome though and googling the issue seems to bring up a lot of Firefox users so perhaps their implementation is incomplete.

For what it's worth, one person suggested disabling fingerprint protection in firefox. That didn't fix it for me.

**Comment by afiaka87** [comment]
> I've been wanting to test 192+ kbps audio. 

I'm about to upload some videos I recorded of some ~700 kbps FLAC (variable bit rate) running under n=4096, is=16384 and fps=500. I'll post a link here when they're done. 

> I hear your complain about the error messages. In fact, I've been trying to debug this thing on Firefox Android and been thinking about a good way to display console logs with errors.

Looks like you've already improved this with the log file download. Thanks.

**Comment by soundshader** [comment]
With a 700 kbps audio input, you'd want a very high `n` param, as it sets the sliding window in samples to detect periodic patterns within that window. Typically, for a 48 kbps audio, I'd set `n=2048` which internally sets the window size to 4096 samples = 4096/48000 = 85 ms = 12 Hz. This means that every circle on the ACF image would represent 85 ms of sound, and that would be enough to detect periodic patterns as low as 24 Hz (you need at least full wave period within that interval, so 85/2ms would be say positive and 85/2ms would be negative). If we translate 85 ms to 700 kbps, we'll get 58000 samples, rounded up to 65536, as it has to work with the FFT algorithm. The app implements a GPU version of the `N*log(N)` Cooley-Tukey FFT, so it probably won't be too bad. I'd try to increase the `n` param step by step to `n=32768`, to avoid surprise glitches.

`is=16384` is crazy high, but may be reasonable. If you set `n=32768`, the app would internally create a ACF height map of size `65536x65536` and then it would map it to polar coordinates onto an image of size `is=16384`. Given that 65536 != 16384, it would downsample the ACF height map first by running the 2x2 -> 1x1 downsampler twice.

`fps=500` really just sets the interval for `setInterval()` timer, 2 ms in your case. IIRC, `setInterval()` won't accept values lower than 4 ms, hence the `fps=250` limit. However if it displays `500 fps` in the top left, then it worked.

Anyways, that's just my guess and the optimal params for a 700 kbps input may be different. Here's the full list of such params:

https://github.com/soundshader/soundshader.github.io/blob/master/vargs.js

**Comment by soundshader** [comment]
FYI, you can customize the color scheme a bit: `?acf.cs=2&acf.rgb=2,4,3`. The default value is `?acf.cs=1&acf.rgb=1,2,4`.

**Comment by afiaka87** [comment]
Oh wow, thanks for the color scheme parameters! I saw vargs.js but wasn't sure which things you had prepared for people to actually change.  Still dusting off my js skills.

>I'd try to increase the n param step by step to n=32768, to avoid surprise glitches.

Looks like there's a hard limit on 16384. I'm getting this error:

`Failed to set the 'fftSize' property on 'AnalyserNode': The FFT size provided (65536) is outside the range [32, 32768]`

Whenever I go over n=16384 (say, to n=32768). I understand this is because the sample size specified gets doubled before being passed to the fft algorithm. I'm guess the FFT you're using has a hard limit of 32768 for sample size? 

It's been my experience (with plain ole FFT in foobar2000's spectrogram, not ACF), that increasing the sample size beyond 8096 starts to have diminishing returns or can even cause problems. Is this not the case with ACF? Or is it really just a case-by-case thing where you'll only get more out of it with a higher sample rate?

**Comment by soundshader** [comment]
Ah, right, I use `AnalyserNode.getFloatTimeDomainData` to read the audio buffer, and size of that buffer is set via `fftSize`, despite I'm not using `AnalyserNode` to perform FFT.

FFT is applied to a slice of waveform of certain duration. The longer that duration the fuzzier FFT gets, but it's also able to detect more periodic patterns. The optimal duration is indeed around 8192 samples at 48 kHz rate. But what really matters is the duration of the slice in seconds, so if the sample rate goes to 96 kHz, we'd need to use 16384 samples per FFT call.

FYI, the color params have changed a bit: `acf.c1=4,2,1&acf.c2=1,2,4` sets the two colors for positive and negative ACF values. To actually see two different colors, use the `acf.cs=2` color scheme, as the default one colors both signs the same way.

**Comment by soundshader** [comment]
FYI, I've added the precise sampling mode: https://github.com/soundshader/soundshader.github.io/commit/d218847ffc244329befea6d161ac5d96b6219f79

Most music out there doesn't have enough details to fill this super-resolution. In my collection, only some pieces by D. Parsons have this much details:

![512](https://user-images.githubusercontent.com/71118651/98065650-d579cb80-1e09-11eb-86a7-6f037a21c632.jpg)

2048x2048: https://github.com/soundshader/soundshader.github.io/blob/master/pics/parsons-2.jpg
