### ISSUE TITLE
Motion Aftereffect can be disorienting

### ISSUE THREAD

**Issue by afiaka87** [soundshader/soundshader.github.io#3]
Not an issue so much as a notice to others who find themselves staring at visualizers for minutes on end.

Doing so with soundshader pretty consistently results in an optical phenomenon known as motion aftereffect in which static imagery appears to shift for awhile. It can be a bit jarring if you're not expecting it, so just letting folks know. 

https://en.wikipedia.org/wiki/Motion_aftereffect has some info on the subject

**Comment by soundshader** [comment]
Ha, it absolutely does cause this effect. Using a lower `fps=50` values would make the "movie" slow and also would capture 30-60 sec of sound on the image, at the expense of losing microscopic details. In other words, you'd see the big picture of sound at the 30-60 sec altitude.
