### ISSUE TITLE
Downsample from stereo to mono instead of using just one track

### ISSUE THREAD

**Issue by afiaka87** [soundshader/soundshader.github.io#5]
I noticed here that it looks like you're only capturing the left (I think? or is 0 the right side?) channel of the audio track - 

https://github.com/soundshader/soundshader.github.io/blob/a72719cbd6e3fb2cc85965d353d489879b340054/audio/cwt.js#L22

Is it possible to downsample both tracks to mono instead in order to get any missing audio from the other channel for stereo-heavy tracks?

What about visualizing both channels simultaneously?

**Comment by afiaka87** [comment]
I believe the code snippet here does the trick actually - 

```javascript
let dest = new AudioBuffer(channels, source.length, {context: options.context});
let left = source.getChannelData(0);
let right = source.getChannelData(1);
for (let i = 0, l = dest.length; i < l; i++) {
  dest[i] = .5 * (left[i] + right[i]);
}
```
https://github.com/audiojs/audio-buffer-remix/blob/b519fc3b40eb2a887c7cf3025663f0074aa8c663/index.js#L20
found from the following library.

**Comment by soundshader** [comment]
Hmm, just averaging the two channels? I can give it a try.

Rendering both channels separately is tricky because of the limited screen space. One idea is to render both ACF images and mix them together on the screen, but I'm afraid the result will be a fuzzy mess (it may be a spectacular success too - you never know).

Edit: That `cwt.js` file is the continuous wavelet transform. I was exploring that idea before ACF. You can enable it with `s=cwt`. I haven't moved it to GPU, so it's very slow.

**Comment by soundshader** [comment]
Actually, the current implementation (`controller.js`) seems to do the right thing - it down-mixes both channels to one mono channel. Found this on stackoverflow:

> If the MediaStream has multiple channels (stereo, say), AnalyserNode mixes them to mono. You'll need to split out the MediaStream data (using a ChannelSplitterNode to get the track you want and send that to the analyser.

What you're referring to is code in CWT that preloads the entire audio file and reads an exact slice of the waveform with `getChannelData`.

There's still a potential problem that `getFloatTimeDomainData` used by the app is less accurate than `getChannelData`, so the app visualizes a slightly corrupted waveform. I can try adding a mode that uses `getChannelData`, just to see if there's a difference in quality.

**Comment by afiaka87** [comment]
> 
> > Actually, the current implementation (`controller.js`) seems to do the right thing - it down-mixes both channels to one mono channel. Found this on stackoverflow:

Ah, my mistake! Thanks for clearing that up.

> There's still a potential problem that `getFloatTimeDomainData` used by the app is less accurate than `getChannelData`, so the app visualizes a slightly corrupted waveform. I can try adding a mode that uses `getChannelData`, just to see if there's a difference in quality.

I would hope that the browser API's for this are accurate. Is there reason to believe they aren't?

Slightly related -

Is it correct that the polar coordinates have a vertical symmetry? Is that coming from a deliberate mirroring to "complete the circle", or is it actually an emergent property of mapping ACF to polar coordinates?

**Comment by soundshader** [comment]
ACF images are symmetric and periodic because ACF is an even periodic function, like `cos(t)`. In fact, ACF is a linear combination of `cos(wt)` functions.
