### ISSUE TITLE
with hss, option to generate whole spectrum of a long sound and save result

### ISSUE THREAD

**Issue by ghost** [soundshader/soundshader.github.io#8]
In the /hss view, Instead of using the A and D key to display part of the spectrum that is not visible on the canvas, would it be possible to generate the whole spectrum of a sound (of any length) and save it in a (png) file?

**Comment by ghost** [comment]
I found a simple solution: in hss.js, on line 305, I set the length of the viewport to the length of the sound buffer: aviewport.len = audio32.length;

**Comment by soundshader** [comment]
You can zoom it out with "S" if I remember correctly.
